import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib

#Load csv generated by encode.py
df = pd.read_csv("data/processed/astronauts_scores.csv")

#Drop everything but name and overall score
X = df.drop(columns=['Name', 'OverallScore'])
y = df['OverallScore']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("RMSE:", mean_squared_error(y_test, y_pred, squared=False))
print("R^2:", r2_score(y_test, y_pred))

#Dump model
joblib.dump(model, "models/random_forest_model.pkl")
print("Model saved to models/random_forest_model.pkl")